#! /bin/sh

pgrep -u $USER -x sxhkd > /dev/null || sxhkd &

DISPLAY1=eDP
#DISPLAY2=HDMI-A-0
DISPLAY2=DisplayPort-0

xrandr --output $DISPLAY1 --mode 1920x1080
xrandr --output $DISPLAY2 --primary --mode 1920x1080 --right-of $DISPLAY1

bspc monitor $DISPLAY1 -d 0
bspc monitor $DISPLAY2 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         1
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

$HOME/.config/polybar/launch.sh
